### PR TITLE
Implement HTTPS

### LINKED ISSUE #20: HTTPS?
Congrats on the launch! Any chance of moving the site to [HTTPS-only](https://https.cio.gov/everything/)? It'd be a great way to lead by example for the rest of the city.

### PR DESCRIPTION
**Pull request by thekaveman**
The cert has already been applied to Azure site, so this loads: https://analytics.smgov.net

This PR does 2 things:

  - Permanently redirects requests for the HTTP version, to the HTTPS version
  - Updates the config URLs so e.g. generated data URLs use HTTPS

Closes #20

### CODE REVIEW

**Comment by allejo** [comment]
Have all city websites been moved to HTTPS or only a few? There are a few instances in our JS file that we assume HTTP. In the [`feature/domain-selector-47`](https://github.com/CityofSantaMonica/analytics.smgov.net/tree/feature/domain-selector-47) branch, I'll be changing it so it's defined on a per site basis

**Comment by thekaveman** [comment]
Ah, I had not noticed that but seeing it now. 

So *most* of our sites have been moved to HTTPS - but definitely not all of them *yet*.

I think your approach to define on a per-site basis for #47 is correct. Let me know when you have something setup and I can go in and define those that are already HTTPS.

**Comment by allejo** [comment]
Take a look at e31f75d1563a57b6924083a67e6e817f08fd8592, that's where we'll be defining which protocol the website uses. Once that's been updated, I can extract that portion of the branch and merge it into master so it won't be blocked by the domain selector functionality which still needs to be finished.

**Review by allejo — APPROVED** [review]

**Comment by thekaveman** [comment]
Ok, check out 0ecbd7c

**Comment by allejo** [comment]
Does anything else need to be done on Azure? I've merged in #52 so links on the site now use the correct protocol

**Comment by thekaveman** [comment]
I *think* the Azure setup should be good. 

Didn't we test this before? Setting up a secondary slot in Azure and deploying to that? Otherwise I'm not sure how else to see if its working other than... merge it

**Comment by allejo** [comment]
Sweet, looks like it worked!

**Comment by thekaveman** [comment]
Baller!

**Comment by konklone** [comment]
:ta-da: Great work! This is a great move for Santa Monica, and I hope it's a trend for.the city. :)

**Pull request merged**
