### PR TITLE
Add www to ANALYTICS_HOSTNAME.

### PR DESCRIPTION
**Pull request by smcor3dump**
@thekaveman Add 'www' to checked in files. One file for smcitynet.com left alone since there is no redirect in place. Do we want to implement a redirect?

### CODE REVIEW

**Comment by thekaveman** [comment]
@smcor3dump yes I think so, we should redirect that site to `www` as well.

**Comment by smcor3dump** [comment]
@thekaveman smcitynet.com now 301 to www.smcitynet.com and update ANALYTICS_HOSTNAME to reflect www.

**Comment by smcor3dump** [comment]
Accidentally closed issue, reopening.

**Comment by thekaveman** [comment]
GTG :+1: 

Closes #27

**Pull request merged**
