### PR TITLE
Socrata webjob refactor

### LINKED ISSUE #28: Enable Travis caching?
E.g. for `bundler` (where I feel like the majority of the build time is spent anyway)

https://docs.travis-ci.com/user/caching/

### LINKED ISSUE #32: Look at moving to Python 3

### LINKED ISSUE #42: Socrata WebJob doesn't meet new SNI requirement
**Background:** [SNI now required for HTTPS connections](https://dev.socrata.com/changelog/2016/08/24/sni-now-required-for-https-connections.html) and socrata/discuss#30

**Error:** We're now seeing failures in the `socrata` WebJob, with the following output

```
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Status changed to Initializing
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Run script 'run.py' with script host - 'PythonScriptHost'
[08/31/2016 08:30:04 > 4f9adc: SYS INFO] Status changed to Running
[08/31/2016 08:30:21 > 4f9adc: ERR ] D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS 
is not available on this platform. This may cause the server to present an incorrect TLS certificate, 
which can cause validation failures. You can upgrade to a newer version of Python to solve this. 
For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
[08/31/2016 08:30:21 > 4f9adc: ERR ]   SNIMissingWarning
[08/31/2016 08:30:21 > 4f9adc: ERR ] D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning:
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately
and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to 
solve this. For more information, see
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
[08/31/2016 08:30:21 > 4f9adc: ERR ]   InsecurePlatformWarning
[08/31/2016 08:30:21 > 4f9adc: ERR ] Traceback (most recent call last):
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "run.py", line 78, in <module>
[08/31/2016 08:30:21 > 4f9adc: ERR ]     soda_client.upsert(os.environ["SOCRATA_RESOURCEID"], chunk)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 222, in upsert
[08/31/2016 08:30:21 > 4f9adc: ERR ]     return self._perform_update("post", resource, payload)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 239, in _perform_update
[08/31/2016 08:30:21 > 4f9adc: ERR ]     data=json.dumps(payload))
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\sodapy\__init__.py", line 281, in _perform_request
[08/31/2016 08:30:21 > 4f9adc: ERR ]     response = getattr(self.session, request_type)(uri, **kwargs)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 518, in post
[08/31/2016 08:30:21 > 4f9adc: ERR ]     return self.request('POST', url, data=data, json=json, **kwargs)
[08/31/2016 08:30:21 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 475, in request
[08/31/2016 08:30:21 > 4f9adc: ERR ]     resp = self.send(prep, **send_kwargs)
[08/31/2016 08:30:22 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\sessions.py", line 585, in send
[08/31/2016 08:30:22 > 4f9adc: ERR ]     r = adapter.send(request, **kwargs)
[08/31/2016 08:30:22 > 4f9adc: ERR ]   File "D:\home\site\wwwroot\pyenv\lib\python2.7\site-packages\requests\adapters.py", line 477, in send
[08/31/2016 08:30:22 > 4f9adc: ERR ]     raise SSLError(e, request=request)
[08/31/2016 08:30:22 > 4f9adc: ERR ] requests.exceptions.SSLError: hostname 'data.smgov.net' doesn't match 'wxyz.example.org'
[08/31/2016 08:30:22 > 4f9adc: SYS INFO] Status changed to Failed
[08/31/2016 08:30:22 > 4f9adc: SYS ERR ] Job failed due to exit code 1
```

**Possible solution:** (if we are stuck with this version of Python) socrata/dev.socrata.com#594 and [this SO post](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484)

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #32 
Closes #42 

Incidentally, now that we are running Travis in a python environment, this also closes #28

### CODE REVIEW

**Comment by thekaveman** [comment]
@allejo take a look. I got the test slot to run `daily`, then `aggregate`, then `socrata`, all comlpeted successfully.

**Comment by allejo** [comment]
So the `socrata` job is no longer affected by https://github.com/CityofSantaMonica/analytics.smgov.net/issues/42#issuecomment-245385047?

**Comment by thekaveman** [comment]
Right, it was just a few typos with parenthesis and comma placement. `socrata` runs fine now, check it out:

```
https://data.smgov.net/resource/8dh4-6epx.json?$where=date = '2016-09-06T00:00:00' AND domain = 'www.bigbluebus.com'&$order= pageviews DESC
```

**Comment by allejo** [comment]
lgtm 👍

**Comment by allejo** [comment]
I think I might have merged this a bit too soon? Deployment failed

**Comment by thekaveman** [comment]
Yes, too soon. I still needed to revert those `.travis.yml` changes that were made for the slot testing.

In the future, let's say that the person that opens the PR merges/closes the PR. Everyone else is just reviewing.

**Comment by allejo** [comment]
My bad! but that sounds good 👍

**Pull request merged**
